---
# tasks file for docker-installation/
- name: Wait for automatic system updates
  become: true
  shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 1; done;
  with_items:
    - lock
    - lock-frontend

- name: Install packages for docker repository setup
  package: 
   name: 
     - ca-certificates 
     - curl 
     - gnupg 
     - lsb-release
   state: present

- name: Creation keyring directory 
  file: 
    path: /etc/apt/keyrings
    state: directory 
    mode: '0755' 

- name: install docker gpg key 
  shell: 
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes

- name: Install docker repository 
  lineinfile: 
    path: /etc/apt/sources.list.d/docker.list
    create: yes
    line: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   focal stable

- name: Update apt repository metadata
  shell: "apt update" 

- name: Install docker 
  package: 
    name: 
     - docker-ce
     - docker-ce-cli
     - containerd.io
     - docker-compose-plugin
    state: present
